### ISSUE TITLE
Pods folder missing

### ISSUE THREAD

**Issue by wellkunnected** [adrianchifor/Flipcam-iOS#1]
Hi,

Where is the folder labeled "pods" ? This app won't build without it, for some reason with the latest version of Xcode the old way of installing pods does not work, you have to include the pods folder with all the architecture for the pods to work within the app. I'd like to try the app out so please resubmit with actual pods folders included. Thanks for your help!

**Comment by adrianchifor** [comment]
You can get the 'Pods' folder by going into the project folder and running

```
pod install
```

Make sure you have CocoaPods installed.

After the command is done, open Flipcam.xcworkspace and build.

FYI: The instructions to build the app using Xcode 7.2 are in the Readme in the 'Build' section.

**Comment by wellkunnected** [comment]
I understand that but this is the old way of installing pods, if you look
at other projects on github that use cocoapods they usually include the
actual pods folder, it just makes things easier when trying to build and
run the app. In my experience with projects that only had instructions to
run "pod install" it never works. When opening the workspace file in xcode
the "pods" file alway shows up in red letting me know the dependancies for
the pods file are missing. It's simply easier to include the pods folder
with your project but I assume it's more work because for some reason
projects like yours are missing them.

On Thu, Mar 10, 2016 at 9:09 AM, Adrian Chifor notifications@github.com
wrote:

> You can get the 'Pods' folder by going into the project folder and running
> 
> pod install
> 
> Make sure you have CocoaPods installed.
> 
> After the command is done, open Flipcam.xcworkspace and build.
> 
> FYI: The instructions to build the app using Xcode 7.2 are in the Readme
> in the 'Build' section.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adrianchifor/Flipcam-iOS/issues/1#issuecomment-194860487
> .

## 

Founded Well Kunnected, Inc 2010

**Comment by adrianchifor** [comment]
It works fine for me with pod install and then normal build. Anyway, I included the Pods folder :+1:

**Comment by wellkunnected** [comment]
Awesome! I'll give it another try, thanks for your help ✌️
